export const sample_foods = [
    {
      id: '1',
      name: 'tas biru 1',
      cookTime: '10-20',
      price: 100000,
      favorite: false,
      origins: ['italy'],
      stars: 4.5,
      imageUrl: 'foto-1.jpg',
      tags: ['Dewasa', 'Pria', 'Remaja'],
    },
    {
      id: '2',
      name: 'tas hitam 1',
      price: 250000,
      cookTime: '20-30',
      favorite: true,
      origins: ['persia', 'middle east', 'china'],
      stars: 4,
      imageUrl: 'foto-2.jpg',
      tags: ['Remaja', 'wanita'],
    },
    {
      id: '3',
      name: 'tas putih 1',
      price: 550000,
      cookTime: '10-15',
      favorite: false,
      origins: ['germany', 'us'],
      stars: 3.5,
      imageUrl: 'foto-3.jpg',
      tags: ['Unisex', 'Remaja'],
    },
    {
      id: '4',
      name: 'tas hitam 2',
      price: 200000,
      cookTime: '15-20',
      favorite: true,
      origins: ['belgium', 'france'],
      stars: 3,
      imageUrl: 'foto-4.jpg',
      tags: ['Pria', 'Dewasa'],
    },
    {
      id: '5',
      name: 'tas pink 1',
      price: 110000,
      cookTime: '40-50',
      favorite: false,
      origins: ['india', 'asia'],
      stars: 3.5,
      imageUrl: 'foto-5.jpg',
      tags: ['Anak-anak', 'Favorit'],
    },
    {
      id: '6',
      name: 'tas putih 2',
      price: 500000,
      cookTime: '40-50',
      favorite: false,
      origins: ['italy'],
      stars: 4.0,
      imageUrl: 'foto-6.jpg',
      tags: ['Remaja', 'Dewasa', 'Wanita'],
    },
    
  ];

  export const sample_tags = [
    { name: 'All', count: 6},
    { name: 'Dewasa', count: 4},
    { name: 'Remaja', count: 2},
    { name: 'Anak-anak', count: 3},
    { name: 'Wanita', count: 3},
    { name: 'Pria', count: 2},
    { name: 'Unisex', count: 1},
    { name: 'Favorit', count: 1},
  ];